#!/bin/bash

pooja="i love you pranu"

echo "from curent scripts: $pooja"

echo "current pid : $$"

echo "calling other script"


   ./2

echo "after calling other script: $pooja"

source ./2

echo "after calling other script: $pooja"